// @ts-nocheck
import React, { createContext, useContext, useState } from 'react';

export type Language = 'en' | 'ru' | 'uz';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('ru');

  const t = (key: string): string => {
    const currentTranslations = translations[language];
    const fallbackTranslations = translations['en'];
    
    if (currentTranslations && key in currentTranslations) {
      return currentTranslations[key as keyof typeof currentTranslations];
    }
    
    if (fallbackTranslations && key in fallbackTranslations) {
      return fallbackTranslations[key as keyof typeof fallbackTranslations];
    }
    
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}

const translations = {
  en: {
    // Header
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.catalog': 'Catalog',
    'nav.tenders': 'Tenders',
    'nav.contact': 'Contact',
    
    // Hero
    'hero.title': 'Reliable Supply of Oil & Gas and Industrial Equipment',
    'hero.badge': 'Official dealer of leading manufacturers',
    'hero.title.main': 'Reliable supplies',
    'hero.title.highlight': 'oil & gas and industrial',
    'hero.title.end': 'equipment',
    'hero.subtitle.text': 'From selection to commissioning and service',
    'hero.scrollIndicator': 'Scroll down',
    'hero.cta.primary': 'Get Quote',
    'hero.cta.secondary': 'Learn More',
    
    // About
    'about.title': 'About TAMEXGROUP Company',
    'about.description': 'TAMEXGROUP — a modern trading and engineering company, serving as an official dealer and authorized representative of leading manufacturers of oil & gas and industrial equipment. We provide direct equipment supplies from manufacturers, ensuring compliance with all technical requirements and quality standards. Thanks to direct partnerships with manufacturers, we guarantee optimal delivery times, transparent cooperation conditions and technical support at all project stages. TAMEXGROUP acts as a reliable partner for industrial enterprises of Uzbekistan and CIS countries, providing comprehensive supply support — from equipment selection to commissioning and service maintenance.',
    'about.founded': 'Founded',
    'about.founded_desc': 'TAMEXGROUP',
    'about.clients': 'Major Clients',
    'about.clients_desc': '20+',
    'about.quality': 'Supply Quality',
    'about.quality_desc': '100%',
    'about.support': 'Support',
    'about.support_desc': '24/7',
    'about.leadership': 'Leadership',
    'about.ceo': 'CEO',
    'about.ceo_name': 'Kim Alexander Igorevich',
    'about.standards': 'Quality Standards',
    'about.standards_desc': 'API, GOST, TR TS',
    'about.geography': 'Geography',
    'about.geography_desc': 'Uzbekistan, CIS',
    'about.industrialPhotoAlt': 'Oil & gas equipment and technologies',
    'about.industrialTechnologies': 'Industrial Technologies',
    'about.oilGasIndustry': 'Oil & Gas Industry',
    'about.oilGasEquipment': 'Oil & Gas Equipment',
    'about.directSupplies': 'Direct supplies from manufacturers',
    'about.b2bAudience': 'B2B Target Audience',
    'about.b2bAudienceDesc': 'Procurement specialists, engineers, technical specialists and tender departments of major oil & gas and industrial enterprises',
    'about.directContracts': 'Direct Contracts',
    'about.directContractsDesc': 'Established direct partnerships with manufacturers. Supply of standard and specialized equipment',
    'about.growthProspects': 'Growth Prospects',
    'about.growthProspectsDesc': 'Geography: Uzbekistan with prospects for expansion to CIS countries (Kazakhstan, Turkmenistan, Tajikistan, Russia)',
    
    // Mission
    'mission.title': 'Mission and Values',
    'mission.description': 'Our mission is to serve as an official dealer of leading manufacturers of oil & gas and industrial equipment, ensuring timely deliveries, transparent working conditions and long-term partnerships.',
    'mission.reliability.title': 'Reliability',
    'mission.reliability.desc': 'Stable supply quality and reliable service for our partners',
    'mission.innovation.title': 'Direct Supply',
    'mission.innovation.desc': 'Direct contracts with manufacturers without intermediaries',
    'mission.partnership.title': 'Partnership',
    'mission.partnership.desc': 'Long-term relationships based on transparency and mutual benefit',
    'mission.quality.title': 'Quality',
    'mission.quality.desc': 'Compliance with international standards API, GOST, TR TS',
    'mission.badge': 'Official dealer of leading manufacturers of oil & gas and industrial equipment',
    
    // Services
    'services.title': 'Our Products',
    'services.description': 'Comprehensive industrial equipment solutions across various categories',
    'services.catalogButton': 'Product Catalog',
    'services.wellhead.title': 'Wellhead Equipment',
    'services.wellhead.desc': 'Complete wellhead equipment for oil and gas wells, including christmas trees, tubing heads, and casing heads. Designed to withstand extreme pressures and temperatures, ensuring safe and efficient well operation.',
    'services.bop.title': 'Blowout Prevention Equipment',
    'services.bop.desc': 'Advanced blowout prevention systems and well control equipment. Annular and ram-type BOPs with hydraulic control systems, providing maximum safety during drilling operations.',
    'services.pumps.title': 'Pumps and Compressors',
    'services.pumps.desc': 'High-performance centrifugal pumps for oil & gas industry. Multi-stage pumps with magnetic drive options, designed for harsh operating conditions and corrosive fluids.',
    'services.pipes.title': 'Pipes and Fittings',
    'services.pipes.desc': 'Premium carbon and stainless steel pipes with various connection types. Seamless and welded pipes meeting international standards API 5L, ASTM A106, and ASTM A312.',
    'services.instruments.title': 'Instrumentation',
    'services.instruments.desc': 'Precision control and measuring instruments and automation systems. Pressure transmitters, flow meters, temperature sensors, and SCADA systems for process control.',
    'services.drilling.title': 'Drilling Equipment',
    'services.drilling.desc': 'Complete drilling equipment and tools including drill pipes, collars, and stabilizers. High-strength materials for deep well drilling and harsh geological conditions.',
    'services.heat_exchangers.title': 'Heat Exchangers',
    'services.heat_exchangers.desc': 'Efficient shell and tube and plate heat exchangers for various process applications. Custom designs for oil cooling, gas processing, and heat recovery systems.',
    'services.compressors.title': 'Compressors',
    'services.compressors.desc': 'Industrial compressor units for LPG and natural gas processing. Reciprocating and screw compressors with variable speed drives for energy efficiency.',
    'services.seals.title': 'Seals',
    'services.seals.desc': 'Advanced dry gas seals for compressors and rotating equipment. Low-emission seals with extended service life, reducing maintenance costs and environmental impact.',
    'services.filters.title': 'Filters',
    'services.filters.desc': 'Stainless steel filter elements',
    'services.drains.title': 'Drain Systems',
    'services.drains.desc': 'Bottom drain and drainage systems',
    'services.condensate.title': 'Condensate Traps',
    'services.condensate.desc': 'Bimetallic and thermodynamic condensate traps',
    'services.cta.title': 'Need Custom Solutions?',
    'services.cta.description': 'We provide adapted equipment solutions for specific industrial requirements. Contact us to discuss your project needs.',
    'services.cta.button': 'Get Custom Quote',
    
    // Catalog
    'catalog.backButton': 'Back to main',
    'catalog.title': 'Product Catalog',
    'catalog.subtitle': 'Complete catalog of our industrial equipment',
    'catalog.viewButton': 'Click to view',
    
    // Tenders
    'tenders.title': 'Tenders and Partners',
    'tenders.description': 'Our track record of successful partnerships and tender achievements',
    'tenders.success.title': 'Successful Tenders',
    'tenders.success.count': '50+',
    'tenders.success.desc': 'This year',
    'tenders.volume.title': 'Total Supply Volume',
    'tenders.volume.count': '$2M+',
    'tenders.volume.desc': 'This year',
    'tenders.delivery.title': 'On-time Delivery',
    'tenders.delivery.count': '99.8%',
    'tenders.delivery.desc': 'Obligations',
    'tenders.partners.title': 'Our Partners',
    'tenders.partners.desc': 'Reliable partnerships with leading organizations',
    'tenders.trustedPartners': 'Trusted by',
    'tenders.partnersDescription': 'Leading oil and gas companies choose TAMEXGROUP as their reliable partner',
    'tenders.partner': 'Partner',
    'tenders.morePartners': 'And 50+ more satisfied clients',
    'tenders.success_story.title': 'Recent Success',
    'tenders.success_story.description': 'Successfully completed a $500K tender for drilling equipment supply to a major oil field development project in Uzbekistan, delivery completed 2 weeks ahead of schedule.',
    
    // Chart
    'chart.months': 'Jan, Feb, Mar, Apr, May, Jun',
    'chart.successfulTenders': 'Successful Tenders',
    'chart.supplyVolume': 'Supply Volume ($M)',
    'chart.tendersCount': 'tenders',
    
    // TenderCards
    'tenderCards.successfulTenders': 'Successful Tenders',
    'tenderCards.volume': '$2M+ volume',
    'tenderCards.onTimeDelivery': 'On-time Delivery',
    'tenderCards.obligations': '99.8% obligations',
    
    // Virtual Assistant
    'assistant.title': 'Virtual Assistant',
    'assistant.open': 'Open virtual assistant',
    'assistant.contactPlaceholder': 'Email or Phone',
    'assistant.emailSubject': 'Message from TAMEXGROUP virtual assistant from',
    'assistant.messageTitle': 'Need help?',
    'assistant.messageText': 'Send us a message and we\'ll respond quickly!',
    
    // Contact
    'contact.title': 'Contact',
    'contact.subtitle': 'We will respond within a business day',
    'contact.description': 'Contact us for industrial equipment needs',
    'contact.formTitle': 'Feedback Form',
    'contact.name': 'Name',
    'contact.namePlaceholder': 'Your name',
    'contact.contact': 'Email or Phone',
    'contact.contactPlaceholder': 'your.email@company.com or +998 90',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Tell us about your requirements...',
    'contact.send': 'Send',
    'contact.sending': 'Sending...',
    'contact.successMessage': 'Message sent successfully! We will contact you soon.',
    'contact.errorMessage': 'Error sending message. Please try again.',
    'contact.privacyNotice': 'By submitting the form, you agree to the privacy policy',
    'contact.phones': 'Phones',
    'contact.email': 'Email',
    'contact.mapTitle': 'Our Locations',
    'contact.tashkentAddress': 'Yakkarasay District, Tashkent, Uzbekistan',
    'contact.tarazAddress': 'Kazakhstan, 080000, Zhambyl region, Taraz city, Makhmut Ashir street, house 19',
    'contact.workingTime': 'Mon-Fri: 9:00-18:00',
    'contact.info.title': 'Contact Information',
    'contact.info.phone': 'Phone',
    'contact.info.email': 'Email',
    'contact.info.locations': 'Locations',
    'contact.info.tashkent': 'Yakkarasay District, Tashkent, Uzbekistan',
    'contact.info.taraz': 'Kazakhstan, 080000, Zhambyl region, Taraz city, Makhmut Ashir street, house 19',
    'contact.offices': 'Our Offices',
    'contact.headOffice': 'Head Office',
    'contact.representativeOffice': 'Representative Office in RK',
    'contact.actions.call': 'Call Now',
    'contact.actions.email': 'Send Email',
    'contact.actions.view': 'View Location',
    'contact.hours.title': 'Working Hours',
    'contact.hours.monday': 'Monday',
    'contact.hours.tuesday': 'Tuesday',
    'contact.hours.wednesday': 'Wednesday',
    'contact.hours.thursday': 'Thursday',
    'contact.hours.friday': 'Friday',
    'contact.hours.saturday': 'Saturday',
    'contact.hours.sunday': 'Sunday',
    'contact.hours.closed': 'Closed',
    'contact.hours.note': 'Emergency support available 24/7',
    'contact.map.title': 'Our Locations',
    'contact.map.tashkent': 'Tashkent Office',
    'contact.map.taraz': 'Taraz Office',
    'contact.map.address': 'Yakkarasay District, Tashkent',
    'contact.map.directions': 'Get Directions',
    'contact.map.mainOffice': 'Main Office',
    'contact.map.branchOffice': 'Branch Office',
    'contact.cta.title': 'Ready to Start Your Project?',
    'contact.cta.description': 'Get in touch with our experts for personalized equipment solutions and competitive pricing.',
    'contact.cta.callNow': 'Call Now',
    'contact.cta.sendEmail': 'Send Email',
    'contact.openForm': 'Open contact form',
    'contact.tooltip': 'Need help? Contact us!',
    'contact.close': 'Close form',
    'contact.form.namePlaceholder': 'Enter your full name',
    'contact.form.companyPlaceholder': 'Enter company name',
    'contact.form.phonePlaceholder': '+998 90 123 45 67',
    'contact.form.emailPlaceholder': 'your.email@company.com',
    'contact.form.messagePlaceholder': 'Tell us about your project requirements...',
    'contact.form.sending': 'Sending...',
    'contact.success': 'Thank you! We\'ll contact you soon.',
    'contact.privacy': 'By submitting this form, you agree to our privacy policy.',
    'contact.methods.telegram': 'Telegram',
    'contact.methods.email': 'Email',
    'contact.methods.vk': 'VKontakte',
    'contact.methods.chat': 'Live Chat',
    
    // Products
    'products.heatExchangers.title': 'Shell and Tube Heat Exchangers',
    'products.heatExchangers.description': 'Efficient shell and tube heat exchangers for various process applications. Custom designs for oil cooling, gas processing, and heat recovery systems.',
    'products.centrifugalPumps.title': 'Centrifugal Pumps for Oil & Gas Industry',
    'products.centrifugalPumps.description': 'High-performance centrifugal pumps for oil & gas industry. Multi-stage pumps with magnetic drive options, designed for harsh operating conditions and corrosive fluids.',
    'products.polyethylenePipes.title': 'Polyethylene Pipe Production Line',
    'products.polyethylenePipes.description': 'Modern polyethylene pipe production lines for high and low pressure applications. Automated quality control and productivity systems.',
    'products.plateHeatExchanger.title': 'Plate Heat Exchanger',
    'products.plateHeatExchanger.description': 'Compact plate heat exchangers with high heat transfer efficiency. Easily disassembled designs for convenient maintenance and cleaning.',
    'products.airCoolerSection.title': 'Air Cooler Heat Exchange Section',
    'products.airCoolerSection.description': 'Heat exchange sections for air cooling units. Efficient cooling of process fluids in oil & gas and chemical industries.',
    'products.industrialRadiator.title': 'Industrial Radiator Heat Exchanger',
    'products.industrialRadiator.description': 'Industrial radiator heat exchangers for cooling systems. Reliable designs for operation in extreme conditions.',
    'products.lpgCompressor.title': 'LPG Compressor Unit',
    'products.lpgCompressor.description': 'Industrial compressor units for LPG and natural gas processing. Reciprocating and screw compressors with variable speed drives for energy efficiency.',
    'products.stainlessFilters.title': 'Stainless Steel Filter Elements',
    'products.stainlessFilters.description': 'Stainless steel filter elements and bag filters for high temperatures. High filtration efficiency and long service life.',
    'products.bottomDrain.title': 'Bottom Drain Unit 150-4',
    'products.bottomDrain.description': 'Bottom drain and drainage systems for industrial applications. Reliable designs for efficient condensate removal.',
    'products.condensateTraps.title': 'Bimetallic and Thermodynamic Condensate Traps',
    'products.condensateTraps.description': 'Modern bimetallic and thermodynamic condensate traps. Automatic condensate removal with minimal steam losses.',
    'products.steelPipes.title': 'Carbon and Stainless Steel Pipes',
    'products.steelPipes.description': 'Premium quality carbon and stainless steel pipes with various connection types. Seamless and welded pipes meeting international standards API 5L, ASTM A106, and ASTM A312.',

    // Footer
    'footer.usefulLinks': 'Useful Links',
    'footer.contactInfo': 'Contact Information',
    'footer.companyInfo': 'Company Information',
    'footer.copyright': 'TAMEXGROUP © All rights reserved',
    'footer.privacyPolicy': 'Personal Data Processing Terms',
    'footer.companyName': 'LLC "Tamex"',
    'footer.inn': 'INN: 311 629 333',
    'footer.mfo': 'MFO: 01028',
    'footer.oked': 'OKED: 4690',
    'footer.links': 'Quick Links',
    'footer.contact': 'Contact Information',
    'footer.follow': 'Follow Us',
    'footer.rights': 'All rights reserved.',
  },
  ru: {
    // Header
    'nav.about': 'О нас',
    'nav.services': 'Услуги',
    'nav.catalog': 'Каталог',
    'nav.tenders': 'Тендеры',
    'nav.contact': 'Контакты',
    
    // Hero
    'hero.title': 'Надёжные поставки нефтегазового и промышленного оборудования',
    'hero.badge': 'Официальный дилер ведущих производителей',
    'hero.title.main': 'Надёжные поставки',
    'hero.title.highlight': 'нефтегазового и промышленного',
    'hero.title.end': 'оборудования',
    'hero.subtitle.text': 'От подбора до ввода в эксплуатацию и сервиса',
    'hero.scrollIndicator': 'Прокрутите вниз',
    'hero.cta.primary': 'Получить предложение',
    'hero.cta.secondary': 'Узнать подробнее',
    
    // About
    'about.title': 'О компании TAMEXGROUP',
    'about.description': 'TAMEXGROUP — современная торгово-инжиниринговая компания, являющаяся официальным дилером и уполномоченным представителем ведущих производителей нефтегазового и промышленного оборудования. Мы осуществляем прямые поставки оборудования от заводов-изготовителей, обеспечивая соответствие продукции всем техническим требованиям и стандартам качества. Благодаря прямым партнёрским отношениям с производителями, мы гарантируем оптимальные сроки поставки, прозрачные условия сотрудничества и техническую поддержку на всех этапах проекта. TAMEXGROUP выступает надёжным партнёром для промышленных предприятий Узбекистана и стран СНГ, обеспечивая комплексное сопровождение поставок — от подбора оборудования до ввода в эксплуатацию и сервисного обслуживания.',
    'about.founded': 'Год основания',
    'about.founded_desc': 'TAMEXGROUP',
    'about.clients': 'Крупных клиентов',
    'about.clients_desc': '20+',
    'about.quality': 'Качество поставок',
    'about.quality_desc': '100%',
    'about.support': 'Поддержка',
    'about.support_desc': '24/7',
    'about.leadership': 'Руководство',
    'about.ceo': 'Генеральный директор',
    'about.ceo_name': 'Ким Александр Игоревич',
    'about.standards': 'Стандарты качества',
    'about.standards_desc': 'API, ГОСТ, ТР ТС',
    'about.geography': 'География',
    'about.geography_desc': 'Узбекистан, СНГ',
    'about.industrialPhotoAlt': 'Нефтегазовое оборудование и технологии',
    'about.industrialTechnologies': 'Промышленные технологии',
    'about.oilGasIndustry': 'Нефтегазовая отрасль',
    'about.oilGasEquipment': 'Нефтегазовое оборудование',
    'about.directSupplies': 'Прямые поставки от производителей',
    'about.b2bAudience': 'Целевая аудитория B2B',
    'about.b2bAudienceDesc': 'Специалисты по закупкам, инженеры, технические специалисты и тендерные отделы крупных нефтегазовых и промышленных предприятий',
    'about.directContracts': 'Прямые контракты',
    'about.directContractsDesc': 'Налаженные прямые партнёрские отношения с заводами-производителями. Поставки стандартного и специализированного оборудования',
    'about.growthProspects': 'Перспективы роста',
    'about.growthProspectsDesc': 'География: Узбекистан с перспективой расширения на страны СНГ (Казахстан, Туркменистан, Таджикистан, Россия)',
    
    // Mission
    'mission.title': 'Наша миссия и ценности',
    'mission.description': 'Наша миссия — быть официальным дилером ведущих производителей нефтегазового и промышленного оборудования, обеспечивая своевременные поставки, прозрачные условия работы и долгосрочные партнёрские отношения.',
    'mission.reliability.title': 'Надежность',
    'mission.reliability.desc': 'Стабильное качество поставок и надёжный сервис для наших партнёров',
    'mission.innovation.title': 'Прямые поставки',
    'mission.innovation.desc': 'Прямые контракты с заводами-производителями без посредников',
    'mission.partnership.title': 'Партнерство',
    'mission.partnership.desc': 'Долгосрочные отношения, основанные на прозрачности и взаимной выгоде',
    'mission.quality.title': 'Качество',
    'mission.quality.desc': 'Соответствие международным стандартам API, ГОСТ, ТР ТС',
    'mission.badge': 'Официальный дилер ведущих производителей нефтегазового и промышленного оборудования',
    
    // Services
    'services.title': 'Наша продукция',
    'services.description': 'Комплексные решения промышленного оборудования по различным категориям',
    'services.catalogButton': 'Каталог товаров',
    'services.wellhead.title': 'Фонтанная арматура',
    'services.wellhead.desc': 'Комплектная фонтанная арматура для нефтяных и газовых скважин, включая фонтанные ёлки, колонные и трубные головки. Оборудование рассчитано на экстремальные давления и температуры, обеспечивая безопасную и эффективную эксплуатацию скважин.',
    'services.bop.title': 'Противовыбросовое оборудование',
    'services.bop.desc': 'Современные системы предотвращения выбросов и контроля скважин. Превенторы кольцевого и плашечного типа с гидравлическими системами управления, обеспечивающие максимальную безопасность при буровых работах.',
    'services.pumps.title': 'Насосы и компрессоры',
    'services.pumps.desc': 'Высокопроизводительные центробежные насосы для нефтегазовой отрасли. Многоступенчатые насосы с магнитным приводом, рассчитанные на жесткие условия эксплуатации и агрессивные среды.',
    'services.pipes.title': 'Трубы и фитинги',
    'services.pipes.desc': 'Трубы премиального качества из углеродистой и нержавеющей стали различных типов соединений. Бесшовные и сварные трубы, соответствующие международным стандартам API 5L, ASTM A106 и ASTM A312.',
    'services.instruments.title': 'КИПиА',
    'services.instruments.desc': 'Прецизионные контрольно-измерительные приборы и системы автоматизации. Датчики давления, расходомеры, датчики температуры и SCADA-системы для управления технологическими процессами.',
    'services.drilling.title': 'Буровое оборудование',
    'services.drilling.desc': 'Комплектное буровое оборудование и инструмент, включая бурильные трубы, утяжеленные бурильные трубы и центраторы. Высокопрочные материалы для глубокого бурения и сложных геологических условий.',
    'services.heat_exchangers.title': 'Теплообменники',
    'services.heat_exchangers.desc': 'Эффективные кожухотрубные и пластинчатые теплообменники для различных технологических применений. Индивидуальное проектирование для охлаждения нефти, переработки газа и систем рекуперации тепла.',
    'services.compressors.title': 'Компрессоры',
    'services.compressors.desc': 'Промышленные компрессорные установки для переработки СУГ и природного газа. Поршневые и винтовые компрессоры с частотно-регулируемым приводом для энергоэффективности.',
    'services.seals.title': 'Уплотнения',
    'services.seals.desc': 'Современные сухие газовые уплотнения для компрессоров и вращающегося оборудования. Низкоэмиссионные уплотнения с увеличенным сроком службы, снижающие затраты на обслуживание и экологическое воздействие.',
    'services.filters.title': 'Фильтры',
    'services.filters.desc': 'Фильтрующие элементы из нержавеющей стали',
    'services.drains.title': 'Сливные установки',
    'services.drains.desc': 'Установки нижнего слива и дренажные системы',
    'services.condensate.title': 'Конденсатоотводчики',
    'services.condensate.desc': 'Биметаллические и термодинамические конденсатоотводчики',
    'services.cta.title': 'Нужны индивидуальные решения?',
    'services.cta.description': 'Мы предоставляем адаптированные решения оборудования для конкретных промышленных требований. Свяжитесь с нами для обсуждения ваших потребностей в проекте.',
    'services.cta.button': 'Получить индивидуальное предложение',
    
    // Catalog
    'catalog.backButton': 'Назад на главную',
    'catalog.title': 'Каталог товаров',
    'catalog.subtitle': 'Полный каталог нашего промышленного оборудования',
    'catalog.viewButton': 'Нажмите для просмотра',
    
    // Tenders
    'tenders.title': 'Тендеры и партнеры',
    'tenders.description': 'Наш послужной список успешных партнерств и тендерных достижений',
    'tenders.success.title': 'Успешных тендеров',
    'tenders.success.count': '50+',
    'tenders.success.desc': 'За текущий год',
    'tenders.volume.title': 'Общий объем поставок',
    'tenders.volume.count': '$2M+',
    'tenders.volume.desc': 'В текущем году',
    'tenders.delivery.title': 'Выполнение в срок',
    'tenders.delivery.count': '99.8%',
    'tenders.delivery.desc': 'Обязательств',
    'tenders.partners.title': 'Наши партнеры',
    'tenders.partners.desc': 'Надежные партнерства с ведущими организациями',
    'tenders.trustedPartners': 'Нам доверяют',
    'tenders.partnersDescription': 'Ведущие компании нефтегазовой отрасли выбирают TAMEXGROUP как надежного партнера',
    'tenders.partner': 'Партнер',
    'tenders.morePartners': 'И еще 50+ довольных клиентов',
    'tenders.success_story.title': 'Недавний успех',
    'tenders.success_story.description': 'Успешно завершили тендер на $500K для поставки бурового оборудования на крупный проект разработки нефтяного месторождения в Узбекистане, поставка выполнена на 2 недели раньше срока.',
    
    // Chart
    'chart.months': 'Янв, Фев, Мар, Апр, Май, Июн',
    'chart.successfulTenders': 'Успешные тендеры',
    'chart.supplyVolume': 'Объем поставок ($M)',
    'chart.tendersCount': 'тендеров',
    
    // TenderCards
    'tenderCards.successfulTenders': 'Успешных тендеров',
    'tenderCards.volume': '$2M+ объем',
    'tenderCards.onTimeDelivery': 'Выполнение в срок',
    'tenderCards.obligations': '99.8% обязательств',
    
    // Virtual Assistant
    'assistant.title': 'Виртуальный помощник',
    'assistant.open': 'Открыть виртуального помощника',
    'assistant.contactPlaceholder': 'Email или телефон',
    'assistant.emailSubject': 'Сообщение от виртуального помощника TAMEXGROUP от',
    'assistant.messageTitle': 'Нужна помощь?',
    'assistant.messageText': 'Отправьте нам сообщение, и мы быстро ответим!',
    
    // Contact
    'contact.title': 'Контакты',
    'contact.subtitle': 'Мы ответим в течение рабочего дня',
    'contact.description': 'Свяжитесь с нами по вопросам промышленного оборудования',
    'contact.formTitle': 'Форма обратной связи',
    'contact.name': 'Имя',
    'contact.namePlaceholder': 'Ваше имя',
    'contact.contact': 'Email или Телефон',
    'contact.contactPlaceholder': 'your.email@company.com или +998 90',
    'contact.message': 'Сообщение',
    'contact.messagePlaceholder': 'Расскажите о ваших требованиях...',
    'contact.send': 'Отправить',
    'contact.sending': 'Отправка...',
    'contact.successMessage': 'Сообщение успешно отправлено! Мы свяжемся с вами в ближайшее время.',
    'contact.errorMessage': 'Ошибка отправки сообщения. Попробуйте еще раз.',
    'contact.privacyNotice': 'Отправляя форму, вы соглашаетесь с политикой конфиденциальности',
    'contact.phones': 'Телефоны',
    'contact.email': 'Email',
    'contact.mapTitle': 'Наши локации',
    'contact.tashkentAddress': 'Яккасарайский район, Ташкент, Узбекистан',
    'contact.tarazAddress': 'Казахстан, 080000, Жамбылская область, г. Тараз, ул. Махмут Аширов, д. 19',
    'contact.workingTime': 'Пн-Пт: 9:00-18:00',
    'contact.info.title': 'Контактная информация',
    'contact.info.phone': 'Телефон',
    'contact.info.email': 'Email',
    'contact.info.locations': 'Локации',
    'contact.info.tashkent': 'Яккасарайский район, Ташкент, Узбекистан',
    'contact.info.taraz': 'Казахстан, 080000, Жамбылская область, г. Тараз, ул. Махмут Аширов, д. 19',
    'contact.offices': 'Наши офисы',
    'contact.headOffice': 'Головной офис',
    'contact.representativeOffice': 'Представительство в РК',
    'contact.actions.call': 'Позвонить',
    'contact.actions.email': 'Написать',
    'contact.actions.view': 'Посмотреть',
    'contact.hours.title': 'Рабочее время',
    'contact.hours.monday': 'Понедельник',
    'contact.hours.tuesday': 'Вторник',
    'contact.hours.wednesday': 'Среда',
    'contact.hours.thursday': 'Четверг',
    'contact.hours.friday': 'Пятница',
    'contact.hours.saturday': 'Суббота',
    'contact.hours.sunday': 'Воскресенье',
    'contact.hours.closed': 'Выходной',
    'contact.hours.note': 'Экстренная поддержка доступна 24/7',
    'contact.map.title': 'Наши офисы',
    'contact.map.tashkent': 'Офис в Ташкенте',
    'contact.map.taraz': 'Офис в Таразе',
    'contact.map.address': 'Яккасарайский район, Ташкент',
    'contact.map.directions': 'Построить маршрут',
    'contact.map.mainOffice': 'Главный офис',
    'contact.map.branchOffice': 'Филиал',
    'contact.cta.title': 'Готовы начать проект?',
    'contact.cta.description': 'Свяжитесь с нашими экспертами для индивидуальных решений и конкурентных цен.',
    'contact.cta.callNow': 'Позвонить',
    'contact.cta.sendEmail': 'Написать',
    'contact.openForm': 'Открыть форму связи',
    'contact.tooltip': 'Нужна помощь? Свяжитесь с нами!',
    'contact.close': 'Закрыть форму',
    'contact.form.namePlaceholder': 'Введите ваше полное имя',
    'contact.form.companyPlaceholder': 'Введите название компании',
    'contact.form.phonePlaceholder': '+998 90 123 45 67',
    'contact.form.emailPlaceholder': 'your.email@company.com',
    'contact.form.messagePlaceholder': 'Расскажите о требованиях вашего проекта...',
    'contact.form.sending': 'Отправка...',
    'contact.success': 'Спасибо! Мы свяжемся с вами в ближайшее время.',
    'contact.privacy': 'Отправляя эту форму, вы соглашаетесь с нашей политикой конфиденциальности.',
    'contact.methods.telegram': 'Telegram',
    'contact.methods.email': 'Email',
    'contact.methods.vk': 'ВКонтакте',
    'contact.methods.chat': 'Онлайн чат',
    
    // Products
    'products.heatExchangers.title': 'Кожухотрубные теплообменники',
    'products.heatExchangers.description': 'Эффективные кожухотрубные теплообменники для различных технологических применений. Индивидуальное проектирование для охлаждения нефти, переработки газа и систем рекуперации тепла.',
    'products.centrifugalPumps.title': 'Центробежные насосы для нефтегазовой отрасли',
    'products.centrifugalPumps.description': 'Высокопроизводительные центробежные насосы для нефтегазовой отрасли. Многоступенчатые насосы с магнитным приводом, рассчитанные на жесткие условия эксплуатации и агрессивные среды.',
    'products.polyethylenePipes.title': 'Линия производства полиэтиленовых труб',
    'products.polyethylenePipes.description': 'Современные линии производства полиэтиленовых труб высокого и низкого давления. Автоматизированные системы контроля качества и производительности.',
    'products.plateHeatExchanger.title': 'Пластинчатый теплообменник',
    'products.plateHeatExchanger.description': 'Компактные пластинчатые теплообменники с высокой эффективностью теплопередачи. Легко разбираемые конструкции для удобного обслуживания и очистки.',
    'products.airCoolerSection.title': 'Теплообменная секция аппарата воздушного охлаждения',
    'products.airCoolerSection.description': 'Секции теплообмена для аппаратов воздушного охлаждения. Эффективное охлаждение технологических жидкостей в нефтегазовой и химической промышленности.',
    'products.industrialRadiator.title': 'Индустриальный радиатор теплообменник',
    'products.industrialRadiator.description': 'Промышленные радиаторные теплообменники для систем охлаждения. Надежные конструкции для работы в экстремальных условиях.',
    'products.lpgCompressor.title': 'Компрессорный агрегат для СУГ',
    'products.lpgCompressor.description': 'Промышленные компрессорные установки для переработки СУГ и природного газа. Поршневые и винтовые компрессоры с частотно-регулируемым приводом.',
    'products.stainlessFilters.title': 'Фильтрующие элементы из нержавеющей стали',
    'products.stainlessFilters.description': 'Фильтрующие элементы из нержавеющей стали и рукавные фильтры для высоких температур. Высокая эффективность фильтрации и долгий срок службы.',
    'products.bottomDrain.title': 'Установка нижнего слива 150-4',
    'products.bottomDrain.description': 'Установки нижнего слива и дренажные системы для промышленного применения. Надежные конструкции для эффективного удаления конденсата.',
    'products.condensateTraps.title': 'Биметаллические и термодинамические конденсатоотводчики',
    'products.condensateTraps.description': 'Современные конденсатоотводчики биметаллического и термодинамического типа. Автоматическое удаление конденсата с минимальными потерями пара.',
    'products.steelPipes.title': 'Трубы из углеродистой и нержавеющей стали',
    'products.steelPipes.description': 'Трубы премиального качества из углеродистой и нержавеющей стали различных типов соединений. Бесшовные и сварные трубы, соответствующие международным стандартам.',

    // Footer
    'footer.usefulLinks': 'Полезные ссылки',
    'footer.contactInfo': 'Контактные данные',
    'footer.companyInfo': 'Информация о компании',
    'footer.copyright': 'TAMEXGROUP © Все права защищены',
    'footer.privacyPolicy': 'Условия обработки персональных данных',
    'footer.companyName': 'ООО «Tamex»',
    'footer.inn': 'ИНН: 311 629 333',
    'footer.mfo': 'МФО: 01028',
    'footer.oked': 'ОКЭД: 4690',
    'footer.links': 'Быстрые ссылки',
    'footer.contact': 'Контактная информация',
    'footer.follow': 'Подписывайтесь',
    'footer.rights': 'Все права защищены.',
  },
  uz: {
    // Header
    'nav.about': 'Biz haqimizda',
    'nav.services': 'Xizmatlar',
    'nav.catalog': 'Katalog',
    'nav.tenders': 'Tenderlar',
    'nav.contact': 'Aloqa',
    
    // Hero
    'hero.title': 'Neft-gaz va sanoat uskunalarining ishonchli etkazib berilishi',
    'hero.badge': 'Yetakchi ishlab chiqaruvchilarning rasmiy dileri',
    'hero.title.main': 'Ishonchli etkazib berish',
    'hero.title.highlight': 'neft-gaz va sanoat',
    'hero.title.end': 'uskunalari',
    'hero.subtitle.text': 'Tanlashdan tortib, ishga tushirish va xizmatgacha',
    'hero.scrollIndicator': 'Pastga aylantiring',
    'hero.cta.primary': 'Taklif olish',
    'hero.cta.secondary': 'Batafsil ma\'lumot',
    
    // About
    'about.title': 'TAMEXGROUP haqida',
    'about.description': 'TAMEXGROUP — zamonaviy savdo-muhandislik kompaniyasi, neft-gaz va sanoat uskunalarining yetakchi ishlab chiqaruvchilarining rasmiy dileri va vakolatli vakili hisoblanadi. Biz zavod-ishlab chiqaruvchilardan to\'g\'ridan-to\'g\'ri uskunalarni etkazib beramiz, mahsulotlarning barcha texnik talablar va sifat standartlariga mos kelishini ta\'minlaymiz. Ishlab chiqaruvchilar bilan to\'g\'ridan-to\'g\'ri hamkorlik munosabatlari tufayli biz optimal etkazib berish muddatlarini, hamkorlikning shaffof shartlarini va loyihaning barcha bosqichlarida texnik qo\'llab-quvvatlashni kafolatlaymiz. TAMEXGROUP O\'zbekiston va MDH mamlakatlarining sanoat korxonalari uchun ishonchli hamkor bo\'lib, uskunalarni tanlashdan tortib, ishga tushirish va xizmat ko\'rsatishgacha bo\'lgan kompleks etkazib berishni ta\'minlaydi.',
    'about.founded': 'Tashkil etilgan yili',
    'about.founded_desc': 'TAMEXGROUP',
    'about.clients': 'Yirik mijozlar',
    'about.clients_desc': '20+',
    'about.quality': 'Etkazib berish sifati',
    'about.quality_desc': '100%',
    'about.support': 'Qo\'llab-quvvatlash',
    'about.support_desc': '24/7',
    'about.leadership': 'Rahbariyat',
    'about.ceo': 'Bosh direktor',
    'about.ceo_name': 'Kim Aleksandr Igorevich',
    'about.standards': 'Sifat standartlari',
    'about.standards_desc': 'API, GOST, TR TS',
    'about.geography': 'Geografiya',
    'about.geography_desc': 'O\'zbekiston, MDH',
    'about.industrialPhotoAlt': 'Neft-gaz uskunalari va texnologiyalar',
    'about.industrialTechnologies': 'Sanoat texnologiyalari',
    'about.oilGasIndustry': 'Neft-gaz sanoati',
    'about.oilGasEquipment': 'Neft-gaz uskunalari',
    'about.directSupplies': 'Ishlab chiqaruvchilardan to\'g\'ridan-to\'g\'ri etkazib berish',
    'about.b2bAudience': 'B2B maqsadli auditoriya',
    'about.b2bAudienceDesc': 'Xaridlar bo\'yicha mutaxassislar, muhandislar, texnik mutaxassislar va yirik neft-gaz va sanoat korxonalarining tender bo\'limlari',
    'about.directContracts': 'To\'g\'ridan-to\'g\'ri shartnomalar',
    'about.directContractsDesc': 'Ishlab chiqaruvchi zavodlar bilan o\'rnatilgan to\'g\'ridan-to\'g\'ri hamkorlik munosabatlari. Standart va ixtisoslashtirilgan uskunalarni etkazib berish',
    'about.growthProspects': 'O\'sish istiqbollari',
    'about.growthProspectsDesc': 'Geografiya: O\'zbekiston MDH mamlakatlariga (Qozog\'iston, Turkmaniston, Tojikiston, Rossiya) kengaytirish istiqbollari bilan',
    
    // Mission
    'mission.title': 'Bizning missiya va qadriyatlarimiz',
    'mission.description': 'Bizning missiyamiz - neft-gaz va sanoat uskunalarining yetakchi ishlab chiqaruvchilarining rasmiy dileri bo\'lib, o\'z vaqtida etkazib berish, shaffof ish sharoitlari va uzoq muddatli hamkorlik munosabatlarini ta\'minlash.',
    'mission.reliability.title': 'Ishonchlilik',
    'mission.reliability.desc': 'Barqaror etkazib berish sifati va hamkorlarimiz uchun ishonchli xizmat',
    'mission.innovation.title': 'To\'g\'ridan-to\'g\'ri etkazib berish',
    'mission.innovation.desc': 'Zavod-ishlab chiqaruvchilar bilan vositachisiz to\'g\'ridan-to\'g\'ri shartnomalar',
    'mission.partnership.title': 'Hamkorlik',
    'mission.partnership.desc': 'Shaffoflik va o\'zaro manfaatga asoslangan uzoq muddatli munosabatlar',
    'mission.quality.title': 'Sifat',
    'mission.quality.desc': 'API, GOST, TR TS xalqaro standartlariga muvofiqlik',
    'mission.badge': 'Neft-gaz va sanoat uskunalarining yetakchi ishlab chiqaruvchilarining rasmiy dileri',
    
    // Services
    'services.title': 'Bizning mahsulotlarimiz',
    'services.description': 'Turli toifalardagi keng qamrovli sanoat uskunalari yechimlari',
    'services.catalogButton': 'Mahsulotlar katalogi',
    'services.wellhead.title': 'Fonkan armatura',
    'services.wellhead.desc': 'Neft va gaz quduqlari uchun to\'liq fonkan armatura, shu jumladan fontan daraxtlari, ustun va quvur boshliqlari. Yuqori bosim va haroratga bardosh beradigan, quduqning xavfsiz va samarali ishlashini ta\'minlaydigan uskunalar.',
    'services.bop.title': 'Qarshi chiqish uskunalari',
    'services.bop.desc': 'Zamonaviy chiqishlarni oldini olish va quduq nazorati tizimlari. Gidravlik boshqaruv tizimlari bilan halqali va plashkali tip preventorlar, burg\'ulash ishlari davomida maksimal xavfsizlikni ta\'minlaydi.',
    'services.pumps.title': 'Nasoslar va kompressorlar',
    'services.pumps.desc': 'Yuqori unumdorlikka ega markazdan qochma nasoslar neft-gaz sanoati uchun. Magnit haydovchiga ega ko\'p bosqichli nasoslar, og\'ir ish sharoitlari va agressiv muhitlar uchun mo\'ljallangan.',
    'services.pipes.title': 'Quvurlar va fitinglar',
    'services.pipes.desc': 'Premium sifatli uglerod va zanglamaydigan po\'lat quvurlar turli ulanish turlari bilan. API 5L, ASTM A106 va ASTM A312 xalqaro standartlariga mos choksiz va payvandlangan quvurlar.',
    'services.instruments.title': 'KIPiA',
    'services.instruments.desc': 'Yuqori aniqlikdagi nazorat-o\'lchash asboblari va avtomatlashtirish tizimlari. Bosim datchiklari, oqim o\'lchagichlar, harorat datchiklari va texnologik jarayonlarni boshqarish uchun SCADA tizimlari.',
    'services.drilling.title': 'Burg\'ulash uskunalari',
    'services.drilling.desc': 'To\'liq burg\'ulash uskunalari va asboblari, jumladan burg\'ulash quvurlari, og\'irlashtirilgan burg\'ulash quvurlari va markazlashtiruvchilar. Chuqur burg\'ulash va murakkab geologik sharoitlar uchun yuqori quvvatli materiallar.',
    'services.heat_exchangers.title': 'Issiqlik almashtirgichlar',
    'services.heat_exchangers.desc': 'Samarali jild-quvur va plastinkali issiqlik almashtirgichlar turli texnologik dasturlar uchun. Neftni sovutish, gazni qayta ishlash va issiqlikni qaytarish tizimlari uchun individual loyihalash.',
    'services.compressors.title': 'Kompressorlar',
    'services.compressors.desc': 'SUG va tabiiy gazni qayta ishlash uchun sanoat kompressor qurilmalari. Energiya samaradorligi uchun chastota bilan boshqariladigan haydovchiga ega porshenli va vintli kompressorlar.',
    'services.seals.title': 'Muhrlar',
    'services.seals.desc': 'Kompressorlar va aylanuvchi uskunalar uchun zamonaviy quruq gaz muhrlari. Kam emissiyali muhrlar uzoq xizmat muddati bilan, texnik xizmat ko\'rsatish xarajatlarini va ekologik ta\'sirni kamaytiradi.',
    'services.filters.title': 'Filtrlar',
    'services.filters.desc': 'Zanglamaydigan po\'latdan filtr elementlari',
    'services.drains.title': 'Drenaj tizimlari',
    'services.drains.desc': 'Pastki drenaj va drenaj tizimlari',
    'services.condensate.title': 'Kondensat tushirgichlar',
    'services.condensate.desc': 'Bimetallik va termodinamik kondensat tushirgichlar',
    'services.cta.title': 'Individual yechimlar kerakmi?',
    'services.cta.description': 'Biz aniq sanoat talablari uchun moslashtirilgan uskuna yechimlarini taqdim etamiz. Loyiha ehtiyojlaringizni muhokama qilish uchun biz bilan bog\'laning.',
    'services.cta.button': 'Individual taklif olish',
    
    // Catalog
    'catalog.backButton': 'Asosiy sahifaga qaytish',
    'catalog.title': 'Mahsulotlar katalogi',
    'catalog.subtitle': 'Bizning sanoat uskunalarimizning to\'liq katalogi',
    'catalog.viewButton': 'Ko\'rish uchun bosing',
    
    // Tenders
    'tenders.title': 'Tenderlar va hamkorlar',
    'tenders.description': 'Muvaffaqiyatli hamkorliklar va tender yutuqlarimizning rekordi',
    'tenders.success.title': 'Muvaffaqiyatli tenderlar',
    'tenders.success.count': '50+',
    'tenders.success.desc': 'Joriy yilda',
    'tenders.volume.title': 'Umumiy etkazib berish hajmi',
    'tenders.volume.count': '$2M+',
    'tenders.volume.desc': 'Joriy yilda',
    'tenders.delivery.title': 'Vaqtida bajarish',
    'tenders.delivery.count': '99.8%',
    'tenders.delivery.desc': 'Majburiyatlar',
    'tenders.partners.title': 'Bizning hamkorlarimiz',
    'tenders.partners.desc': 'Etakchi tashkilotlar bilan ishonchli hamkorliklar',
    'tenders.trustedPartners': 'Bizga ishonishadi',
    'tenders.partnersDescription': 'Neft-gaz sanoatining etakchi kompaniyalari TAMEXGROUPni ishonchli hamkor sifatida tanlaydi',
    'tenders.partner': 'Hamkor',
    'tenders.morePartners': 'Va yana 50+ mamnun mijoz',
    'tenders.success_story.title': 'Yaqinda muvaffaqiyat',
    'tenders.success_story.description': 'O\'zbekistondagi yirik neft koni rivojlantirish loyihasiga burg\'ulash uskunalarini etkazib berish bo\'yicha $500K tenderini muvaffaqiyatli yakunladik, etkazib berish rejadan 2 hafta oldin amalga oshirildi.',
    
    // Chart
    'chart.months': 'Yan, Fev, Mar, Apr, May, Iyun',
    'chart.successfulTenders': 'Muvaffaqiyatli tenderlar',
    'chart.supplyVolume': 'Etkazib berish hajmi ($M)',
    'chart.tendersCount': 'tenderlar',
    
    // TenderCards
    'tenderCards.successfulTenders': 'Muvaffaqiyatli tenderlar',
    'tenderCards.volume': '$2M+ hajm',
    'tenderCards.onTimeDelivery': 'Vaqtida bajarish',
    'tenderCards.obligations': '99.8% majburiyatlar',
    
    // Virtual Assistant
    'assistant.title': 'Virtual yordamchi',
    'assistant.open': 'Virtual yordamchini ochish',
    'assistant.contactPlaceholder': 'Email yoki telefon',
    'assistant.emailSubject': 'TAMEXGROUP virtual yordamchidan xabar',
    'assistant.messageTitle': 'Yordam kerakmi?',
    'assistant.messageText': 'Bizga xabar yuboring, tezda javob beramiz!',
    
    // Contact
    'contact.title': 'Aloqa',
    'contact.subtitle': 'Biz ish kuni davomida javob beramiz',
    'contact.description': 'Sanoat uskunalari ehtiyojlaringiz uchun bog\'laning',
    'contact.formTitle': 'Aloqa formasi',
    'contact.name': 'Ism',
    'contact.namePlaceholder': 'Sizning ismingiz',
    'contact.contact': 'Email yoki Telefon',
    'contact.contactPlaceholder': 'your.email@company.com yoki +998 90',
    'contact.message': 'Xabar',
    'contact.messagePlaceholder': 'Talablaringiz haqida gapiring...',
    'contact.send': 'Yuborish',
    'contact.sending': 'Yuborilmoqda...',
    'contact.successMessage': 'Xabar muvaffaqiyatli yuborildi! Tez orada siz bilan bog\'lanamiz.',
    'contact.errorMessage': 'Xabar yuborishda xatolik. Qaytadan urinib ko\'ring.',
    'contact.privacyNotice': 'Formani yuborish orqali siz maxfiylik siyosatiga rozilik bildirasiz',
    'contact.phones': 'Telefonlar',
    'contact.email': 'Email',
    'contact.mapTitle': 'Bizning manzillarimiz',
    'contact.tashkentAddress': 'Yakkarasay tumani, Toshkent, O\'zbekiston',
    'contact.tarazAddress': 'Qozog\'iston, 080000, Jambul viloyati, Taraz shahri, Maxmut Ashir ko\'chasi, 19 uy',
    'contact.workingTime': 'Dush-Yak: 9:00-18:00',
    'contact.info.title': 'Aloqa ma\'lumotlari',
    'contact.info.phone': 'Telefon',
    'contact.info.email': 'Email',
    'contact.info.locations': 'Manzillar',
    'contact.info.tashkent': 'Yakkarasay tumani, Toshkent, O\'zbekiston',
    'contact.info.taraz': 'Qozog\'iston, 080000, Jambul viloyati, Taraz shahri, Maxmut Ashir ko\'chasi, 19 uy',
    'contact.offices': 'Bizning ofislarimiz',
    'contact.headOffice': 'Bosh ofis',
    'contact.representativeOffice': 'Qozog\'istondagi vakolatxona',
    'contact.actions.call': 'Qo\'ng\'iroq qilish',
    'contact.actions.email': 'Yozish',
    'contact.actions.view': 'Ko\'rish',
    'contact.hours.title': 'Ish vaqti',
    'contact.hours.monday': 'Dushanba',
    'contact.hours.tuesday': 'Seshanba',
    'contact.hours.wednesday': 'Chorshanba',
    'contact.hours.thursday': 'Payshanba',
    'contact.hours.friday': 'Juma',
    'contact.hours.saturday': 'Shanba',
    'contact.hours.sunday': 'Yakshanba',
    'contact.hours.closed': 'Dam olish',
    'contact.hours.note': 'Favqulodda qo\'llab-quvvatlash 24/7 mavjud',
    'contact.map.title': 'Bizning ofislarimiz',
    'contact.map.tashkent': 'Toshkent ofisi',
    'contact.map.taraz': 'Taraz ofisi',
    'contact.map.address': 'Yakkarasay tumani, Toshkent',
    'contact.map.directions': 'Marshrut qurish',
    'contact.map.mainOffice': 'Asosiy ofis',
    'contact.map.branchOffice': 'Filial',
    'contact.cta.title': 'Loyihani boshlashga tayyormisiz?',
    'contact.cta.description': 'Individual uskuna yechimlari va raqobatbardosh narxlarni olish uchun ekspertlarimiz bilan bog\'laning.',
    'contact.cta.callNow': 'Qo\'ng\'iroq qilish',
    'contact.cta.sendEmail': 'Yozish',
    'contact.openForm': 'Aloqa formasini ochish',
    'contact.tooltip': 'Yordam kerakmi? Biz bilan bog\'laning!',
    'contact.close': 'Formani yopish',
    'contact.form.namePlaceholder': 'To\'liq ismingizni kiriting',
    'contact.form.companyPlaceholder': 'Kompaniya nomini kiriting',
    'contact.form.phonePlaceholder': '+998 90 123 45 67',
    'contact.form.emailPlaceholder': 'your.email@company.com',
    'contact.form.messagePlaceholder': 'Loyiha talablaringiz haqida gapiring...',
    'contact.form.sending': 'Yuborilmoqda...',
    'contact.success': 'Rahmat! Tez orada siz bilan bog\'lanamiz.',
    'contact.privacy': 'Ushbu formani yuborish orqali siz bizning maxfiylik siyosatimizga rozilik bildirasiz.',
    'contact.methods.telegram': 'Telegram',
    'contact.methods.email': 'Email',
    'contact.methods.vk': 'VKontakte',
    'contact.methods.chat': 'Onlayn chat',
    
    // Products
    'products.heatExchangers.title': 'Jild-quvur issiqlik almashtirgichlar',
    'products.heatExchangers.description': 'Turli texnologik dasturlar uchun samarali jild-quvur issiqlik almashtirgichlar. Neftni sovutish, gazni qayta ishlash va issiqlikni qaytarish tizimlari uchun individual loyihalash.',
    'products.centrifugalPumps.title': 'Neft-gaz sanoati uchun markazdan qochma nasoslar',
    'products.centrifugalPumps.description': 'Neft-gaz sanoati uchun yuqori unumdorlikka ega markazdan qochma nasoslar. Magnit haydovchiga ega ko\'p bosqichli nasoslar, og\'ir ish sharoitlari va agressiv muhitlar uchun mo\'ljallangan.',
    'products.polyethylenePipes.title': 'Polietilen quvurlar ishlab chiqarish liniyasi',
    'products.polyethylenePipes.description': 'Yuqori va past bosimli dasturlar uchun zamonaviy polietilen quvurlar ishlab chiqarish liniyalari. Avtomatlashtirilgan sifat nazorati va unumdorlik tizimlari.',
    'products.plateHeatExchanger.title': 'Plastinkali issiqlik almashtirgich',
    'products.plateHeatExchanger.description': 'Yuqori issiqlik uzatish samaradorligiga ega ixcham plastinkali issiqlik almashtirgichlar. Qulay texnik xizmat ko\'rsatish va tozalash uchun oson ajratiladigan konstruksiyalar.',
    'products.airCoolerSection.title': 'Havo sovutish apparati issiqlik almashtirish bo\'limi',
    'products.airCoolerSection.description': 'Havo sovutish qurilmalari uchun issiqlik almashtirish bo\'limlari. Neft-gaz va kimyoviy sanoatda texnologik suyuqliklarni samarali sovutish.',
    'products.industrialRadiator.title': 'Sanoat radiator issiqlik almashtirgich',
    'products.industrialRadiator.description': 'Sovutish tizimlari uchun sanoat radiator issiqlik almashtirgichlari. Ekstremal sharoitlarda ishlash uchun ishonchli konstruksiyalar.',
    'products.lpgCompressor.title': 'SUG uchun kompressor agregati',
    'products.lpgCompressor.description': 'SUG va tabiiy gazni qayta ishlash uchun sanoat kompressor qurilmalari. Energiya samaradorligi uchun chastota bilan boshqariladigan haydovchiga ega porshenli va vintli kompressorlar.',
    'products.stainlessFilters.title': 'Zanglamaydigan po\'latdan filtr elementlari',
    'products.stainlessFilters.description': 'Yuqori haroratlar uchun zanglamaydigan po\'latdan filtr elementlari va qop filtrlar. Yuqori filtratsiya samaradorligi va uzoq xizmat muddati.',
    'products.bottomDrain.title': 'Pastki drenaj qurilmasi 150-4',
    'products.bottomDrain.description': 'Sanoat dasturlari uchun pastki drenaj va drenaj tizimlari. Kondensatni samarali olib tashlash uchun ishonchli konstruksiyalar.',
    'products.condensateTraps.title': 'Bimetallik va termodinamik kondensat tushirgichlar',
    'products.condensateTraps.description': 'Zamonaviy bimetallik va termodinamik kondensat tushirgichlar. Minimal bug\' yo\'qotishlari bilan avtomatik kondensat olib tashlash.',
    'products.steelPipes.title': 'Uglerod va zanglamaydigan po\'latdan quvurlar',
    'products.steelPipes.description': 'Turli ulanish turlari bilan premium sifatli uglerod va zanglamaydigan po\'latdan quvurlar. API 5L, ASTM A106 va ASTM A312 xalqaro standartlariga mos choksiz va payvandlangan quvurlar.',

    // Footer
    'footer.usefulLinks': 'Foydali havolalar',
    'footer.contactInfo': 'Aloqa ma\'lumotlari',
    'footer.companyInfo': 'Kompaniya haqida ma\'lumot',
    'footer.copyright': 'TAMEXGROUP © Barcha huquqlar himoyalangan',
    'footer.privacyPolicy': 'Shaxsiy ma\'lumotlarni qayta ishlash shartlari',
    'footer.companyName': 'MChJ «Tamex»',
    'footer.inn': 'INN: 311 629 333',
    'footer.mfo': 'MFO: 01028',
    'footer.oked': 'OKED: 4690',
    'footer.links': 'Tezkor havolalar',
    'footer.contact': 'Aloqa ma\'lumotlari',
    'footer.follow': 'Bizni kuzatib boring',
    'footer.rights': 'Barcha huquqlar himoyalangan.',
  }
};